package br.com.azi.patrimoniomobiliario.domain.usecase.patrimonio.listagemestornados;

import br.com.azi.patrimoniomobiliario.domain.usecase.UseCase;

public interface BuscarPatrimoniosEstornadosPorIncorporacaoUseCase extends UseCase<BuscarPatrimoniosEstornadosPorIncorporacaoInputData, BuscarPatrimoniosEstornadosPorIncorporacaoOutputData> {
}
