package br.com.azi.patrimoniomobiliario.domain.usecase.movimentacao.interna.relatorios.memorando.memorandomovimentacaoemelaboracao;


import br.com.azi.patrimoniomobiliario.domain.usecase.UseCase;

public interface GerarMemorandoMovimentacaoInternaEmElaboracaoUseCase extends UseCase<GerarMemorandoMovimentacaoInternaEmElaboracaoInputData, GerarMemorandoMovimentacaoInternaEmElaboracaoOutputData> {
}
