package br.com.azi.patrimoniomobiliario.domain.usecase.movimentacao.interna.devolucaoalmoxarifado.finalizacao.converter;

import br.com.azi.patrimoniomobiliario.domain.entity.Movimentacao;
import br.com.azi.patrimoniomobiliario.domain.usecase.movimentacao.interna.devolucaoalmoxarifado.finalizacao.FinalizarMovimentacaoDevolucaoAlmoxarifadoOutputData;
import br.com.azi.patrimoniomobiliario.utils.converter.GenericConverter;

public class FinalizarMovimentacaoDevolucaoAlmoxarifadoOutputDataConverter extends GenericConverter<Movimentacao, FinalizarMovimentacaoDevolucaoAlmoxarifadoOutputData> {
}
