package br.com.azi.patrimoniomobiliario.domain.usecase.configuracao.reserva.intervalo.relatorios.termoresponsabilidade;

import br.com.azi.patrimoniomobiliario.domain.usecase.UseCase;

public interface GerarTermoGuardaResponsabilidadeReservaUseCase extends UseCase<GerarTermoGuardaResponsabilidadeReservaInputData, GerarTermoGuardaResponsabilidadeReservaOutputData> {
}
